[toolchain]
anchor_version = "0.30.1"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
zerorouter = "scr8KCMrUgArFL7bamxFccwbYhxRv4qpWb1auhomeSE"

[programs.localnet]
zerorouter = "scr8KCMrUgArFL7bamxFccwbYhxRv4qpWb1auhomeSE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "deploy-wallet.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
